version: '3'
services:
  backend:
    build: .
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=db  # Подключаемся к контейнеру с БД по имени сервиса
      - DB_USER=${DB_USER}
      - DB_NAME=${DB_NAME}
      - DB_PORT=5432  # Порт внутри сети Docker (не меняется)
    
